events {}
http {
    client_max_body_size 50m;
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name _;
        # статика
        location /static/ {
            alias /app/staticfiles/;
        }
        # прокси на gunicorn
        location / {
            proxy_pass http://web:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        # медиа
        location /media/ {
            alias /app/media/;
        }

        location = /favicon.ico {
            alias /app/staticfiles/favicon.ico;
        }
    }
}