# Generated by Django 5.2.7 on 2025-10-15 14:37

import django.db.models.deletion
import temple.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('main', 'Главное изображение'), ('logo', 'Логотип'), ('base_temple', 'Базовое изображение храма'), ('base_clergy', 'Базовое изображение духовенства')], max_length=50, unique=True)),
                ('image', models.ImageField(upload_to=temple.models.BaseImage.upload_to)),
            ],
            options={
                'verbose_name': 'Базовое изображение',
                'verbose_name_plural': 'Базовые изображения',
            },
        ),
        migrations.CreateModel(
            name='Clergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('post', models.CharField(blank=True, max_length=255, null=True, verbose_name='Епархиальные послушания')),
                ('description', models.TextField(null=True, verbose_name='Места служения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='clergy_images', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Духовенство',
                'verbose_name_plural': 'Духовенство',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(null=True, verbose_name='Описание')),
                ('location', models.CharField(max_length=255, verbose_name='Аррес (координаты)')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(max_length=255, verbose_name='Направление деятельнсти')),
                ('image', models.ImageField(blank=True, null=True, upload_to='deal_images', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Деятольеность',
                'verbose_name_plural': 'Деятельность',
            },
        ),
        migrations.CreateModel(
            name='GodServes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название богослужения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='god_serves_images', verbose_name='Изображение расписания богослужения')),
            ],
            options={
                'verbose_name': 'Богослужение',
                'verbose_name_plural': 'Богослужения',
            },
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название таинства')),
                ('description', models.TextField(verbose_name='Описание таинства')),
                ('image', models.ImageField(blank=True, null=True, upload_to='secret_images', verbose_name='Изображение таинства')),
            ],
            options={
                'verbose_name': 'Таинство',
                'verbose_name_plural': 'Таинства',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images', verbose_name='Обложка (изображение)')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('on_main', models.BooleanField(default=False, verbose_name='Главная новость')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='temple.deal', verbose_name='Направление деятельности')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='temple.news')),
            ],
            options={
                'verbose_name': 'Изображение новости',
                'verbose_name_plural': 'Изображения новостей',
            },
        ),
        migrations.CreateModel(
            name='Temple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название храма')),
                ('description', models.TextField(verbose_name='История храма')),
                ('image', models.ImageField(blank=True, null=True, upload_to='temple_images', verbose_name='Изображение храма')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('schedule', models.TextField(verbose_name='Расписание')),
                ('location', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('shcool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temple', to='temple.deal', verbose_name='Воскресная школа')),
            ],
            options={
                'verbose_name': 'Храм',
                'verbose_name_plural': 'Храмы',
            },
        ),
        migrations.CreateModel(
            name='TempleClergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('clergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temple.clergy')),
                ('temple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temple_clergy', to='temple.temple')),
            ],
        ),
        migrations.AddField(
            model_name='temple',
            name='clergy',
            field=models.ManyToManyField(related_name='temple', through='temple.TempleClergy', to='temple.clergy', verbose_name='Свещенослужители'),
        ),
    ]
