# Generated by Django 5.2.7 on 2025-10-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='full_name',
            field=models.CharField(default=2, max_length=255, verbose_name='Полное название таинства'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clergy',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Места служения'),
        ),
        migrations.AlterField(
            model_name='temple',
            name='description',
            field=models.TextField(verbose_name='История'),
        ),
    ]
