# Generated by Django 5.2.7 on 2025-10-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0002_secret_full_name_alter_clergy_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temple',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='temple',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='temple',
            name='schedule',
            field=models.TextField(blank=True, null=True, verbose_name='Расписание'),
        ),
    ]
