# Generated by Django 5.2.7 on 2025-10-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0003_alter_temple_location_alter_temple_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Код карты из конструктора карт'),
        ),
    ]
