# Generated by Django 5.2.7 on 2025-10-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0004_alter_contact_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='short_stream',
            field=models.CharField(default='Деятельность', max_length=255, verbose_name='Краткое названиенаправление деятельнсти'),
        ),
        migrations.AddField(
            model_name='temple',
            name='map',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Код карты из конструктора карт'),
        ),
    ]
