# Generated by Django 5.2.7 on 2025-10-29 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0005_deal_short_stream_temple_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Работает', max_length=255, unique=True, verbose_name='Статус храма')),
            ],
        ),
        migrations.AddField(
            model_name='temple',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temple', to='temple.status', verbose_name='Статус'),
        ),
    ]
