# Generated by Django 5.2.7 on 2025-10-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0006_status_temple_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('order',), 'verbose_name': 'Статус храма', 'verbose_name_plural': 'Статусы храма'},
        ),
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
