# Generated by Django 5.2.7 on 2025-10-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0007_alter_status_options_status_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='clergy',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='clergy_samll_images', verbose_name='Маленькое изображение'),
        ),
    ]
