# Generated by Django 5.2.7 on 2025-10-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0008_clergy_small_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/small', verbose_name='Обложка (изображение)'),
        ),
        migrations.AddField(
            model_name='temple',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='temple_images', verbose_name='Маленькое изображение храма'),
        ),
    ]
