# Generated by Django 5.2.7 on 2025-10-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0009_news_small_image_temple_small_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clergy',
            name='description',
        ),
        migrations.AlterField(
            model_name='clergy',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Сан, ФИ'),
        ),
    ]
