# Generated by Django 5.2.7 on 2025-10-31 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0010_remove_clergy_description_alter_clergy_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clergy',
            name='post',
        ),
    ]
