# Generated by Django 5.2.7 on 2025-10-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0011_remove_clergy_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='clergy',
            name='post',
            field=models.TextField(blank=True, null=True, verbose_name='Епархиальные послушания'),
        ),
    ]
