# Generated by Django 5.2.7 on 2025-11-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0012_clergy_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='clergy',
            name='first_name',
            field=models.CharField(default='Имя', max_length=255, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='clergy',
            name='last_name',
            field=models.CharField(default='Фамилия', max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='clergy',
            name='runk',
            field=models.CharField(choices=[('deacon', 'Дьякон'), ('priest', 'Иерей'), ('archpriest', 'Протоиерей'), ('bishop', 'Епископ')], default='deacon', max_length=255, verbose_name='Сан'),
        ),
    ]
