# Generated by Django 5.2.7 on 2025-11-03 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0013_clergy_first_name_clergy_last_name_clergy_runk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clergy',
            name='name',
        ),
        migrations.AlterField(
            model_name='templeclergy',
            name='clergy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temple.clergy', verbose_name='Священнослужитель'),
        ),
    ]
