# Generated by Django 5.2.7 on 2025-11-10 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0014_remove_clergy_name_alter_templeclergy_clergy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temple',
            name='status',
        ),
        migrations.AlterField(
            model_name='templeclergy',
            name='clergy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clergy_temple', to='temple.clergy', verbose_name='Священнослужитель'),
        ),
    ]
