# Generated by Django 5.2.7 on 2025-11-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0015_remove_temple_status_alter_templeclergy_clergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='temple',
            name='status',
            field=models.CharField(choices=[('active', 'Действующие'), ('restoring', 'Восстанавливающиеся'), ('under_construction', 'Строящиеся'), ('destroyed', 'Разрушенные')], default='active', max_length=50, verbose_name='Статус'),
        ),
    ]
