# Generated by Django 5.2.7 on 2025-11-16 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0017_delete_status_deal_curator'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='sv_curator_image',
            field=models.ImageField(blank=True, null=True, upload_to='curator_images', verbose_name='Изображение светского куратора'),
        ),
        migrations.AddField(
            model_name='deal',
            name='sv_curator_name',
            field=models.CharField(default='Куратор', max_length=255, verbose_name=' Фамилия и Имя светского куратора'),
        ),
        migrations.AddField(
            model_name='deal',
            name='sv_curator_post',
            field=models.CharField(default='Куратор', max_length=255, verbose_name='Должность светского куратора'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='temple.clergy', verbose_name='Куратор из духовенства'),
        ),
    ]
