# Generated by Django 5.2.7 on 2025-11-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0018_deal_sv_curator_image_deal_sv_curator_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='sv_curator_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на сайт или страницу светского куратора'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='sv_curator_post',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность светского куратора'),
        ),
    ]
