# Generated by Django 5.2.7 on 2025-11-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0019_deal_sv_curator_url_alter_deal_sv_curator_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('last_export_at', models.DateTimeField(blank=True, null=True)),
                ('last_export_file', models.CharField(blank=True, max_length=255, null=True)),
                ('last_export_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Лог резервной копии',
                'verbose_name_plural': 'Логи резервных копий',
            },
        ),
    ]
