# Generated by Django 5.2.7 on 2025-11-18 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0020_backuplog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupLog',
        ),
    ]
