# Generated by Django 5.2.7 on 2025-12-15 20:46

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0021_delete_backuplog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temple',
            options={'ordering': (django.db.models.functions.text.Lower('name'),), 'verbose_name': 'Храм', 'verbose_name_plural': 'Храмы'},
        ),
        migrations.AddField(
            model_name='deal',
            name='curator_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals_2', to='temple.clergy', verbose_name='Куратор из духовенства 2'),
        ),
    ]
