# Generated by Django 5.2.7 on 2025-12-25 11:11

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0022_alter_temple_options_deal_curator_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='temple',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='История'),
        ),
    ]
