# Generated by Django 5.2.7 on 2025-12-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0023_alter_deal_description_alter_news_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='sv_curator_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=' Фамилия и Имя светского куратора'),
        ),
    ]
