# Generated by Django 5.2.7 on 2025-12-25 21:07

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0025_alter_contact_email_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'verbose_name': 'Деятельность', 'verbose_name_plural': 'Деятельность'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Код карты из конструктора карт'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='sv_curator_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия и Имя светского куратора'),
        ),
        migrations.AlterField(
            model_name='temple',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='История'),
        ),
    ]
