# Generated by Django 5.2.7 on 2025-11-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backuplog',
            options={'verbose_name': 'Резервная копия', 'verbose_name_plural': 'Резервные копии'},
        ),
        migrations.RemoveField(
            model_name='backuplog',
            name='key',
        ),
        migrations.RemoveField(
            model_name='backuplog',
            name='last_export_count',
        ),
        migrations.RemoveField(
            model_name='backuplog',
            name='last_export_file',
        ),
        migrations.AddField(
            model_name='backuplog',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backuplog',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
